name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Cancel old workflows for PRs (only the most recent workflow can run).
concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

# Avoid workflow-level permissions, instead use job-level permissions.
permissions: {}

jobs:
  ci-nowindows:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - run: ./ci.sh
        shell: bash
      - run: ./ci-stubs.sh
        shell: bash
  ci-windows:
    strategy:
      matrix:
        os: [windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - run: ./ci.sh
        shell: bash
      # don't run ci-stubs on windows, the linker gets mad
